security:
    # Configuration du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition du fournisseur d'utilisateurs (base de données)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls (pare-feu de sécurité)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login   # Route de connexion
                check_path: app_login   # Route de vérification
                default_target_path: "app_home"  # Redirection après connexion réussie
            logout:
                path: app_logout
                target: app_home  # Redirection après déconnexion
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 7 jours
                path: /
                
    # Contrôle des accès par rôle et URL
